env:
  es6: true
  node: true

parserOptions:
  ecmaVersion: 6
  sourceType: module

# Note: Rules are modified using a number that defines what the rule's behavior should be:
# 0 - turn the rule off
# 1 - turn the rule on as a warning (doesn't affect exit code)
# 2 - turn the rule on as an error (exit code is 1 when triggered)
rules:
  semi: [2, always]
  no-extra-semi: 2
  semi-spacing: 2
  comma-spacing: 2
  no-shadow: 1
  no-unused-vars: 1
  no-use-before-define: [2, nofunc]

  # Disabled:
  no-underscore-dangle: 0
  quotes: 0
  strict: 0
